//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Addresses = new HashSet<Address>();
            this.payments = new HashSet<payment>();
        }
    
        public int c_id { get; set; }
        public string c_email { get; set; }
        public string c_mobile { get; set; }
    
        public virtual ICollection<Address> Addresses { get; set; }
        public virtual ICollection<payment> payments { get; set; }
    }
}
