//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int student_id { get; set; }
        public string student_name { get; set; }
        public Nullable<int> country_id { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> state_id { get; set; }
        public Nullable<System.DateTime> birthdate { get; set; }
        public string hobbies { get; set; }
        public string gender { get; set; }
    
        public virtual city city { get; set; }
        public virtual country country { get; set; }
        public virtual state state { get; set; }
    }
}
